# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c98b093b95e1250c8daac35101b4badd7e41d2903970553963396b83b3bc5f7a6616829f0d5390f7497c18003a94145374c9ec103fefc306732efd3dc4735021

test:
  secret_key_base: ebaa4756169e8c76508527ab84141854057acc278856c0f96e1e0e8a205709fbc684c1eb0fc1e21544780269fbfcdbdcb3aa5d3b669f2ae3185bc1dc9bf69516

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
